### ISSUE TITLE
Make error and Segmentation fault on download

### ISSUE THREAD

**Issue by hemangdilip** [mus65/subberthehut#5]
cc -std=gnu99 -Wall -Wextra -pedantic -O2 -D_FORTIFY_SOURCE=2 -I/usr/local/include  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -DVERSION=\"17\"    -c -o subberthehut.o subberthehut.c
subberthehut.c: In function ‘sub_download’:
subberthehut.c:466: warning: ignoring return value of ‘fwrite’, declared with attribute warn_unused_result
cc   subberthehut.o  -L/usr/local/lib   -lxmlrpc_client -lxmlrpc  -lxmlrpc_xmlparse -lxmlrpc_xmltok -lxmlrpc_util -L/usr/local/lib -lcurl  -lglib-2.0 -lz    -o subberthehut

geting above error on make (warning: ignoring return value of ‘fwrite’)

and when i run get
───────────────────────
98 │   │ eng │ Dexter.S06E07.HDTV.XviD-LOL                                      
   │   │     │ └Dexter.S06E07.HDTV.XviD-LOL.HI.srt
───┼───┼─────┼─────────────────────────────────────────────────────────────────────────────────────────
99 │   │ eng │ Dexter.S01E06.Return.To.Sender.HDTV.XviD-LOL                     
   │   │     │ └Dexter.S01E06.Return.To.Sender.hdtv.xvid-lol.srt

downloading to dexte.srt ...
Segmentation fault (core dumped)

**Comment by mus65** [comment]
On what system are you compiling and does this happen on every subtitle or only on some of them?

I just pushed a fix for the missing fwrite return value check (seems like this warning is not triggered on newer glibc versions).

Alhough I wonder why fwrite() would fail on your system, so the actual problem may be somewhere else. If it still crashes, please compile with

    make clean
    CFLAGS=-g make

and then upload the coredump somewhere so I can figure out what is going on.

**Comment by mus65** [comment]
Closing this due to lack of response.

Feel free to reopen if the crash still happens.
